# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OSM_SAA
                                 A QGIS plugin
 OSM_SAA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-09-01
        copyright            : (C) 2019 by PhDGeomatic
        email                : 
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OSM_SAA class from file OSM_SAA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OSM_SAA import OSM_SAA
    return OSM_SAA(iface)
